
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/savexdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SERVER_PORT: 8443
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./pom.xml
          target: /app/pom.xml
          action: sync
    ports:
      - "443:8443"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - savex_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: savexdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: savex_user
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - savex_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 10s
      retries: 5


networks:
  savex_network:
    driver: bridge